# Generated by Django 3.1.8 on 2021-04-13 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_auto_20210413_0709"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="defectivereturn",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="inventoryadjustment",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="rentrequest",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="rentreturn",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="quantity",
        ),
    ]
