# Generated by Django 3.1.8 on 2021-04-13 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210413_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentrequest',
            name='penalty_fee',
        ),
    ]
