# Generated by Django 3.1.8 on 2021-04-13 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_auto_20210413_1619"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movement",
            old_name="cost",
            new_name="price",
        ),
        migrations.RenameField(
            model_name="movement",
            old_name="profit",
            new_name="unit_price",
        ),
    ]
