# Generated by Django 3.1.8 on 2021-04-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_auto_20210413_1720"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movement",
            name="movement_type",
            field=models.IntegerField(
                choices=[
                    (1, "SALE"),
                    (2, "RENT"),
                    (3, "RENT_RETURN"),
                    (4, "DEFECTIVE_RETURN"),
                    (5, "PURCHASE"),
                    (6, "ADJUSTMENT"),
                ]
            ),
        ),
    ]
