# Generated by Django 3.1.8 on 2021-04-13 22:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0011_auto_20210413_1815'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseOrder',
            new_name='Order',
        ),
        migrations.AlterField(
            model_name='movement',
            name='movement_type',
            field=models.IntegerField(choices=[(1, 'SALE'), (2, 'RENT'), (3, 'RENT_RETURN'), (4, 'DEFECTIVE_RETURN'), (5, 'PURCHASE'), (6, 'ADJUSTMENT_ADD'), (7, 'ADJUSTMENT_REMOVE')]),
        ),
    ]
