# Generated by Django 3.1.8 on 2021-04-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_auto_20210413_2204"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.IntegerField(
                choices=[
                    (1, "SALE"),
                    (2, "RENT"),
                    (3, "RENT_RETURN"),
                    (4, "DEFECTIVE_RETURN"),
                    (5, "PURCHASE"),
                    (6, "ADJUSTMENT_ADD"),
                    (7, "ADJUSTMENT_REMOVE"),
                ],
                default=1,
            ),
        ),
    ]
