# Generated by Django 3.1.8 on 2021-04-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_order_order_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_state",
            field=models.IntegerField(
                choices=[
                    (0, "DRAFT"),
                    (1, "PENDING_REVIEW"),
                    (2, "REJECTED"),
                    (3, "ACCEPTED"),
                    (4, "DEFECTIVE_RETURN"),
                    (5, "PURCHASE"),
                    (6, "ADJUSTMENT"),
                ],
                default=0,
            ),
        ),
    ]
