# Generated by Django 3.1.8 on 2021-04-14 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0017_auto_20210414_1604"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movement",
            name="movement_type",
        ),
    ]
