# Generated by Django 3.1.8 on 2021-04-14 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0018_remove_movement_movement_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movement",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="store.order",
            ),
        ),
    ]
