# Generated by Django 3.1.8 on 2021-04-17 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_remove_movie_movements'),
        ('store', '0022_auto_20210415_0340'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movement',
            unique_together={('movie', 'order')},
        ),
    ]
