# Generated by Django 3.1.8 on 2021-04-17 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20210417_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='user',
        ),
    ]
