# Generated by Django 3.1.8 on 2021-04-14 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20210413_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='movie_purchase',
            new_name='movements',
        ),
    ]
