# Generated by Django 3.1.8 on 2021-04-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20210414_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_state',
            field=models.IntegerField(choices=[(0, 'DRAFT'), (1, 'PENDING_REVIEW'), (2, 'REJECTED'), (3, 'ACCEPTED')], default=0),
        ),
    ]
