# Generated by Django 3.1.8 on 2021-04-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_auto_20210413_0757"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="imdb_id",
            field=models.CharField(
                max_length=25, verbose_name="IMDB ID used to fetch information"
            ),
        ),
        migrations.AddConstraint(
            model_name="movie",
            constraint=models.UniqueConstraint(
                condition=models.Q(is_deleted=False),
                fields=("imdb_id",),
                name="unique_if_not_deleted",
            ),
        ),
    ]
