# Generated by Django 3.1.8 on 2021-04-13 16:43

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20210413_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rent_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
