# Generated by Django 3.1.8 on 2021-04-13 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_movie_rent_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="base_price_policy",
            field=models.IntegerField(
                choices=[(1, "Average"), (2, "Highest")], default=1
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="profit_percentage",
            field=models.FloatField(
                default=0,
                help_text="Will be applied to base price, based on pase price policy",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Profit percentage for this movie",
            ),
        ),
    ]
