# Generated by Django 3.1.8 on 2021-04-13 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0008_auto_20210413_1815"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="movements",
        ),
    ]
