# Generated by Django 3.1.8 on 2021-04-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20210418_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
