# Generated by Django 3.1.8 on 2021-04-18 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0011_movie_is_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="is_deleted",
        ),
    ]
