# Generated by Django 3.1.8 on 2021-04-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20210418_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
